// <auto-generated />
using System;
using DentalSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentalSystem.Infrastructure.Migrations
{
    [DbContext(typeof(DentalSystemDbContext))]
    [Migration("20260120122704_InitialCreate_Specialty")]
    partial class InitialCreate_Specialty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DentalSystem.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpecialtyId");

                    b.ToTable("Specialty");
                });

            modelBuilder.Entity("DentalSystem.Domain.Entities.Treatment", b =>
                {
                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TreatmentId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Treatment");
                });

            modelBuilder.Entity("DentalSystem.Domain.Entities.Specialty", b =>
                {
                    b.OwnsOne("DentalSystem.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("SpecialtyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.HasKey("SpecialtyId");

                            b1.ToTable("Specialty");

                            b1.WithOwner()
                                .HasForeignKey("SpecialtyId");
                        });

                    b.OwnsOne("DentalSystem.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("SpecialtyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("SpecialtyId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Specialty");

                            b1.WithOwner()
                                .HasForeignKey("SpecialtyId");
                        });

                    b.OwnsOne("DentalSystem.Domain.ValueObjects.LifecycleStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("SpecialtyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasColumnName("IsActive");

                            b1.HasKey("SpecialtyId");

                            b1.ToTable("Specialty");

                            b1.WithOwner()
                                .HasForeignKey("SpecialtyId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("DentalSystem.Domain.Entities.Treatment", b =>
                {
                    b.HasOne("DentalSystem.Domain.Entities.Specialty", null)
                        .WithMany("Treatments")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DentalSystem.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("TreatmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.HasKey("TreatmentId");

                            b1.ToTable("Treatment");

                            b1.WithOwner()
                                .HasForeignKey("TreatmentId");
                        });

                    b.OwnsOne("DentalSystem.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TreatmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("TreatmentId");

                            b1.ToTable("Treatment");

                            b1.WithOwner()
                                .HasForeignKey("TreatmentId");
                        });

                    b.OwnsOne("DentalSystem.Domain.ValueObjects.LifecycleStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("TreatmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit")
                                .HasColumnName("IsActive");

                            b1.HasKey("TreatmentId");

                            b1.ToTable("Treatment");

                            b1.WithOwner()
                                .HasForeignKey("TreatmentId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("DentalSystem.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
